#pragma once

#define KLEDR_CTL CTL_CODE(0XCCEE, 0x910, METHOD_BUFFERED, FILE_ANY_ACCESS)


typedef struct _DATA_TRANSFERE_FROM_USER
{
	wchar_t dataFromUser[100] = { 0 };

}DATA_TRANSFERE_FROM_USER, *PDATA_TRANSFERE_FROM_USER;

typedef struct _DATA_TRANSFERE_FROM_KERNEL
{
	wchar_t dataFromKernel[100] = { 0 };

}DATA_TRANSFERE_FROM_KERNEL,*PDATA_TRANSFERE_FROM_KERNEL;